<script setup lang="ts">
import { computed } from 'vue'
import Card from 'primevue/card'
import type { IncidentAnalysis, IncidentSeverity } from '@/types/incident'

const props = defineProps<{
  analysis: IncidentAnalysis
}>()

interface SeverityMeta {
  label: string
  icon: string
  modifier: string
}

const SEVERITY_META: Record<IncidentSeverity, SeverityMeta> = {
  LOW: { label: 'Low', icon: 'pi pi-info-circle', modifier: 'is-low' },
  MEDIUM: { label: 'Medium', icon: 'pi pi-exclamation-circle', modifier: 'is-medium' },
  HIGH: { label: 'High', icon: 'pi pi-exclamation-triangle', modifier: 'is-high' },
  CRITICAL: { label: 'Critical', icon: 'pi pi-bolt', modifier: 'is-critical' },
}

const severity = computed<SeverityMeta>(
  () => SEVERITY_META[props.analysis.severity] ?? SEVERITY_META.MEDIUM,
)

interface AnalysisField {
  key: 'rootCause' | 'impact' | 'recommendation'
  title: string
  icon: string
}

const FIELDS: readonly AnalysisField[] = [
  { key: 'rootCause', title: 'Root Cause', icon: 'pi pi-search' },
  { key: 'impact', title: 'Impact', icon: 'pi pi-chart-line' },
  { key: 'recommendation', title: 'Recommendation', icon: 'pi pi-wrench' },
]
</script>

<template>
  <section class="analysis" aria-label="Incident analysis result">
    <header class="analysis__header">
      <div class="analysis__heading">
        <i class="pi pi-bolt analysis__icon" aria-hidden="true"></i>
        <div>
          <h2 class="analysis__title">Analysis result</h2>
          <p class="analysis__subtitle">Generated by OpsMind AI</p>
        </div>
      </div>

      <span class="severity-badge" :class="severity.modifier">
        <span class="severity-badge__dot" aria-hidden="true"></span>
        <i :class="severity.icon" aria-hidden="true"></i>
        <span>{{ severity.label }} severity</span>
      </span>
    </header>

    <div class="analysis__grid">
      <Card v-for="field in FIELDS" :key="field.key" class="analysis-card">
        <template #title>
          <span class="analysis-card__title">
            <i :class="field.icon" aria-hidden="true"></i>
            {{ field.title }}
          </span>
        </template>
        <template #content>
          <p class="analysis-card__text">{{ props.analysis[field.key] }}</p>
        </template>
      </Card>
    </div>
  </section>
</template>

<style scoped>
.analysis {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.analysis__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  flex-wrap: wrap;
}

.analysis__heading {
  display: inline-flex;
  align-items: center;
  gap: 0.85rem;
}

.analysis__icon {
  width: 42px;
  height: 42px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: 1.3rem;
  color: var(--om-accent);
  border-radius: 12px;
  background: rgba(56, 189, 248, 0.12);
  border: 1px solid rgba(56, 189, 248, 0.25);
}

.analysis__title {
  font-size: 1.15rem;
}

.analysis__subtitle {
  margin-top: 0.1rem;
  color: var(--om-text-dim);
  font-size: 0.8rem;
}

.severity-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.45rem 0.9rem;
  border-radius: 999px;
  font-weight: 600;
  font-size: 0.82rem;
  border: 1px solid transparent;
}

.severity-badge__dot {
  width: 9px;
  height: 9px;
  border-radius: 50%;
  background: currentColor;
  box-shadow: 0 0 0 4px rgba(255, 255, 255, 0.06);
}

.severity-badge.is-low {
  color: var(--om-sev-low);
  background: rgba(52, 211, 153, 0.12);
  border-color: rgba(52, 211, 153, 0.3);
}

.severity-badge.is-medium {
  color: var(--om-sev-medium);
  background: rgba(251, 191, 36, 0.12);
  border-color: rgba(251, 191, 36, 0.3);
}

.severity-badge.is-high {
  color: var(--om-sev-high);
  background: rgba(251, 146, 60, 0.12);
  border-color: rgba(251, 146, 60, 0.3);
}

.severity-badge.is-critical {
  color: var(--om-sev-critical);
  background: rgba(248, 113, 113, 0.14);
  border-color: rgba(248, 113, 113, 0.35);
}

.analysis__grid {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(min(100%, 280px), 1fr));
}

.analysis-card {
  height: 100%;
}

.analysis-card__title {
  display: inline-flex;
  align-items: center;
  gap: 0.55rem;
  font-size: 0.98rem;
  font-weight: 600;
  color: var(--om-text);
}

.analysis-card__title i {
  color: var(--om-accent);
}

.analysis-card__text {
  color: var(--om-text-muted);
  font-size: 0.92rem;
  line-height: 1.65;
  white-space: pre-line;
}
</style>
